In [1]:
# Importing libraries

import requests
from bs4 import BeautifulSoup
from csv import writer

In [2]:
# Base url

url = "https://www.imdb.com/list/ls533015232/"

In [3]:
# Requesting Url

page = requests.get(url)

soup = BeautifulSoup(page.content, 'html.parser')

In [4]:
# Parent node

lists = soup.find_all('div',class_= "lister-item")

In [5]:
# Extracting File

with open ('southindia_movies_22.csv', 'w', encoding='utf8', newline='') as f:
    thewriter = writer(f)
    header = ['index','title','year','runtime','genre','rating','description','director','actors','votes','language','budget','worldwide_gross','worldwide_share','domestic_nett','verdict']
    thewriter.writerow(header)
    for list in lists:
         
         index = list.find('span',class_="lister-item-index").text

         title1 = list.find('h3', class_="lister-item-header")
         title = title1.find('a', href=True).text

         year = list.find('span',class_="lister-item-year").text

         runtime = list.find('span',class_="runtime").text
    
         genre = list.find('span',class_="genre").text
    
         rating = list.find('span',class_="ipl-rating-star__rating").text

         description = list.find('p', class_="").text

         team = list.findAll('p', class_="text-muted text-small")
         lo0 = team[1]
         director = lo0.find('a', href=True).text

         l1 = list.findAll('p', class_="text-muted text-small")
         l2 = l1[1]
         l3 = l2.findAll('a')
         actor1 = l3[1].text.strip()
         actor2 = l3[2].text.strip()
         actor3 = l3[3].text.strip()
         actor4 = l3[4].text.strip()
         actors = [actor1, actor2, actor3, actor4]
    

         l1 = list.findAll('p', class_="text-muted text-small")
         l2 = l1[2]
         l3 = l2.findAll('span', )
         l4 = l3[1]
         l6 = l4['data-value']
         votes = l6


         l1 = list.find('div', class_="list-description")
         p = l1.find('p')
         language = p.contents[0].split(':')[1]
         budget = p.contents[3].split(':')[1]
         worldwide_gross = p.contents[6].split(':')[1]
         worldwide_share = p.contents[9].split(':')[1]
         domestic_nett = p.contents[12].split(':')[1]
         verdict = p.contents[15].split(':')[1]




         info = [index,title, year, runtime, genre, rating, description, director,
                  actors, votes, language, budget, worldwide_gross, worldwide_share, domestic_nett, verdict]
         thewriter.writerow(info)

In [6]:
# loading extracted dataset set

import pandas as pd
df = pd.read_csv("southindia_movies_22.csv")
df.head()

,index,title,year,runtime,genre,rating,description,director,actors,votes,language,budget,worldwide_gross,worldwide_share,domestic_nett,verdict
0,1.0,RRR,(2022),187 min,"\nAction, Adventure, Drama",7.9,\nA fictitious story about two legendary revol...,S.S. Rajamouli,"['N.T. Rama Rao Jr.', 'Ram Charan', 'Ajay Devg...",138799,Telugu,425cr,1208.5cr,638.4cr,784.2cr,Blockbuster
1,2.0,K.G.F: Chapter 2,(2022),168 min,"\nAction, Crime, Drama",8.3,"\nIn the blood-soaked Kolar Gold Fields, Rocky...",Prashanth Neel,"['Yash', 'Sanjay Dutt', 'Raveena Tandon', 'Sri...",137374,Kannada,150cr,1207.9cr,600.8cr,855.3cr,All Time Blockbuster
2,3.0,Ponniyin Selvan: Part One,(2022),167 min,"\nAction, Adventure, Drama",7.7,\nVandiyathevan sets out to cross the Chola la...,Mani Ratnam,"['Vikram', 'Aishwarya Rai Bachchan', 'Jayam Ra...",31311,Tamil,210cr,490.6cr,238.1cr,278.2cr,Blockbuster
3,4.0,Vikram,(2022),175 min,"\nAction, Crime, Thriller",8.3,\nA high-octane action film where a special in...,Lokesh Kanagaraj,"['Kamal Haasan', 'Vijay Sethupathi', 'Fahadh F...",62014,Tamil,115cr,420.5cr,213.5cr,255.4cr,Double Blockbuster
4,5.0,Kantara,(2022),148 min,"\nAction, Adventure, Drama",8.3,\nIt involves culture of Kambala and Bhootha K...,Rishab Shetty,"['Rishab Shetty', 'Kishore Kumar G.', 'Achyuth...",91950,Kannada,15cr,393.3cr,189.8cr,305.5cr,Double Blockbuster

In [7]:
# Shape of data

df.shape

(53, 16)

In [8]:
# Data  Cleaning

df['index'] = df['index'].astype(object)
df['title'] = df['title'].str.strip()
df['year'] = df['year'].str.strip('( ) I')
df['runtime'] = df['runtime'].str.strip(' min').astype(int)
df['genre'] = df['genre'].str.strip()
df['rating'] = df['rating'].astype(float)
df['description'] = df['description'].str.strip()
df['director'] = df['director'].str.strip()
df['actors'] = df['actors'].str.strip('[]').astype(str)
df['votes'] = df['votes'].astype(int)
df['language'] = df['language'].str.strip()
df['budget'] = df['budget'].str.strip('cr ').astype(int)
df['worldwide_gross'] = df['worldwide_gross'].str.strip('cr ').astype(float)
df['worldwide_share'] = df['worldwide_share'].str.strip('cr ').astype(float)
df['domestic_nett'] = df['domestic_nett'].str.strip('cr ').astype(float)
df['verdict'] = df['verdict'].str.strip()

In [9]:
# Checking for null values

df.isnull().sum()

index              0
title              0
year               0
runtime            0
genre              0
rating             0
description        0
director           0
actors             0
votes              0
language           0
budget             0
worldwide_gross    0
worldwide_share    0
domestic_nett      0
verdict            0
dtype: int64

In [10]:
# Dataset informaton 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            53 non-null     object
 1   title            53 non-null     object
 2   year             53 non-null     object
 3   runtime          53 non-null     int64
 4   genre            53 non-null     object
 5   rating           53 non-null     float64
 6   description      53 non-null     object
 7   director         53 non-null     object
 8   actors           53 non-null     object
 9   votes            53 non-null     int64
 10  language         53 non-null     object
 11  budget           53 non-null     int64
 12  worldwide_gross  53 non-null     float64
 13  worldwide_share  53 non-null     float64
 14  domestic_nett    53 non-null     float64
 15  verdict          53 non-null     object
dtypes: float64(4), int64(3), object(9)
memory usage: 6.8+ KB

In [11]:
# description of data set

df.describe()

,runtime,rating,votes,budget,worldwide_gross,worldwide_share,domestic_nett
count,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000
mean,153.377358,6.683019,20786.433962,59.905660,136.498113,70.524528,92.411321
std,14.819720,1.419471,30363.226661,73.079584,234.166306,119.653103,157.875392
min,121.000000,2.700000,1453.000000,5.000000,20.500000,10.400000,11.500000
25%,146.000000,5.600000,4423.000000,15.000000,46.500000,22.100000,27.100000
50%,151.000000,7.000000,9273.000000,35.000000,65.200000,34.600000,45.500000
75%,163.000000,7.700000,27596.000000,65.000000,102.000000,53.600000,75.600000
max,187.000000,8.900000,138799.000000,425.000000,1208.500000,638.400000,855.300000

In [12]:
df.head()

,index,title,year,runtime,genre,rating,description,director,actors,votes,language,budget,worldwide_gross,worldwide_share,domestic_nett,verdict
0,1.0,RRR,2022,187,"Action, Adventure, Drama",7.9,A fictitious story about two legendary revolut...,S.S. Rajamouli,"'N.T. Rama Rao Jr.', 'Ram Charan', 'Ajay Devgn...",138799,Telugu,425,1208.5,638.4,784.2,Blockbuster
1,2.0,K.G.F: Chapter 2,2022,168,"Action, Crime, Drama",8.3,"In the blood-soaked Kolar Gold Fields, Rocky's...",Prashanth Neel,"'Yash', 'Sanjay Dutt', 'Raveena Tandon', 'Srin...",137374,Kannada,150,1207.9,600.8,855.3,All Time Blockbuster
2,3.0,Ponniyin Selvan: Part One,2022,167,"Action, Adventure, Drama",7.7,Vandiyathevan sets out to cross the Chola land...,Mani Ratnam,"'Vikram', 'Aishwarya Rai Bachchan', 'Jayam Rav...",31311,Tamil,210,490.6,238.1,278.2,Blockbuster
3,4.0,Vikram,2022,175,"Action, Crime, Thriller",8.3,A high-octane action film where a special inve...,Lokesh Kanagaraj,"'Kamal Haasan', 'Vijay Sethupathi', 'Fahadh Fa...",62014,Tamil,115,420.5,213.5,255.4,Double Blockbuster
4,5.0,Kantara,2022,148,"Action, Adventure, Drama",8.3,It involves culture of Kambala and Bhootha Kol...,Rishab Shetty,"'Rishab Shetty', 'Kishore Kumar G.', 'Achyuth ...",91950,Kannada,15,393.3,189.8,305.5,Double Blockbuster